### PR TITLE
Add ARM64 support

### PR DESCRIPTION
**Pull request by hmartinez82**

### CODE REVIEW

**Comment by hmartinez82** [comment]
Looking

**Review by jrfonseca — CHANGES_REQUESTED** [review]
Please rebase over 99b3224d061b6e2d499382f643692934e32f4049 which fixes a recent issue with GitHub Actions build-cross job.

Otherwise PR looks good.  Thanks!

**Comment by hmartinez82** [comment]
@jrfonseca Rebased, and updated the CHECK_STDERR lines

**Comment by jrfonseca** [comment]
Thanks!

**Pull request merged**
