### PR TITLE
mgwhelp: Add Unicode stubs for some DbgHelp APIs

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Is debugging 32-bit target processes from a 64-bit debugger process supported? Doesn't seem to work.

**Comment by jrfonseca** [comment]
> From a quick test, Very Sleepy seems to work fine with these additions.

Great. Thanks.

> Is debugging 32-bit target processes from a 64-bit debugger process supported? Doesn't seem to work.

It should in theory. But in practice I too struggled to get 64bits DrMingw to handle 32bits processes.  But I don't know if the bug was in DrMingw's code, or MgwHelp's code.

> Also, what is binutils needed for?

Not strictly needed.  It can be optionally used for historic reasons: e.g., old MinGW produced binaires in STABS format, because there was a time where my libdwarf integration was flaky, and just for comparison.

But the hope is indeed that we'll just used libdwarf eventually.

**Comment by jrfonseca** [comment]
> Is debugging 32-bit target processes from a 64-bit debugger process supported? Doesn't seem to work.

FYI, this is now fixed with 0d51507455381dd69c786bcd26a9da1c15122a88 .

**Comment by CyberShadow** [comment]
Awesome, thanks.

**Pull request closed without merging**
